### ISSUE TITLE
How to use this GitHub action?

### ISSUE THREAD

**Issue by spier** [xt0rted/markdownlint-problem-matcher#74]
Hi there,

I tried to use this GitHub Action, as specified:

```
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xt0rted/markdownlint-problem-matcher@v1
      - run: markdownlint **/*.md --ignore node_modules
```

But when the action runs, I get the error:
```
line 1: markdownlint: command not found
```

So I suspect I must be doing something completely wrong?

**Comment by xt0rted** [comment]
This action doesn't include markdownlint, it's just to parse linting errors from the build log.

If you're already running markdownlint as part of your build process then replace the run step with a call to your build script, otherwise you'll also need to install the markdownlint-cli package.

```yml
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xt0rted/markdownlint-problem-matcher@v1
      - run: npm install -g markdownlint-cli
      - run: markdownlint **/*.md --ignore node_modules
```

I'm using this as part of an npm script which is also how it's setup in this repo:

https://github.com/xt0rted/markdownlint-problem-matcher/blob/79ddf94ec121c5f936b20e0570aa7fdde7cbaebc/package.json#L10

https://github.com/xt0rted/markdownlint-problem-matcher/blob/79ddf94ec121c5f936b20e0570aa7fdde7cbaebc/.github/workflows/ci.yml#L28
